RWA-532: Functional Tests
hmcts/wa-case-event-handler pull request #147
Opened 2021-05-24 13:23 UTC by alexbaeza

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RWA-532
https://tools.hmcts.net/jira/browse/RWA-310

### Change description ###

Added functional tests 

**Does this PR introduce a breaking change?** (check one with "x")

```
[ x] Yes
[ ] No
```

2021-06-01 11:17 UTC, indvamshi requested changes

2021-06-01 11:17 UTC, indvamshi commented on src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
> +
caseCategory should be null, is there a way to verify it?

2021-06-14 13:34 UTC, iguannago approved these changes

2021-06-14 13:38 UTC, indvamshi approved these changes
A minor comment to be clarified.

2021-06-14 13:38 UTC, indvamshi commented on src/functionalTest/java/uk/gov/hmcts/reform/wacaseeventhandler/controllers/CaseEventHandlerControllerTest.java
> +
Cant we add this, .body("__processCategory__caseProgression.value", isNull));

2021-06-14 13:38 UTC, merged