RWA-2049 new message job for setting message state
hmcts/wa-case-event-handler pull request #434
Opened 2022-12-06 15:46 UTC by DennisHoV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-2049

### Change description ###
- new message job for setting message state

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-12-07 10:42 UTC, raghera requested changes
Looks good in general but take a look at the feedback.

2022-12-07 10:42 UTC, raghera commented on src/main/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/SetMessageStateMessageJob.java
> +        if (this.messageIds == null || this.messageIds.isEmpty() || !canRun(SET_MESSAGE_STATE_MESSAGES)) {
Could all these conditions be wrapped in the `canRun` method?

2022-12-12 16:43 UTC, dharmendrak submitted a review, later dismissed

2022-12-13 10:31 UTC, raghera submitted a review, later dismissed
Looks good.

2022-12-23 16:44 UTC, serdaroguzhanakin approved these changes

2022-12-23 17:09 UTC, raghera requested changes
Think the test needs updating?

2022-12-23 17:09 UTC, raghera commented on src/test/java/uk/gov/hmcts/reform/wacaseeventhandler/services/jobservices/SetStateToProcessedMessageJobTest.java
> +        assertEquals(MessageState.PROCESSED,unprocessableMessage.getState());
surely this should be checking the list of messages returned from the `run()` method?

2023-01-05 10:05 UTC, raghera approved these changes

2023-01-05 13:16 UTC, merged